[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "./railway-start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100

[nixpacks]
nodejs = "20"

[variables]
PORT = "5000"
NODE_ENV = "production"