services:
  - type: web
    name: omnigovern-dao
    env: node
    buildCommand: bash ./render-build.sh
    startCommand: bash ./render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    disk:
      name: omnigovern-data
      mountPath: /data
      sizeGB: 1

databases:
  - name: omnigovern-db
    plan: free
    ipAllowList: []